services:

  app:
    env_file:
      - .env

    build:
      .

    ports:
      - "8002:8000"
    
    volumes:
      - ./app:/usr/src/app

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
