"""initial migration

Revision ID: 31cab90e4add
Revises:
Create Date: 2026-08-22 15:05:39.603436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31cab90e4add"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("task_deadline", sa.Date(), nullable=False),
        sa.Column("task_detail", sa.Text(), nullable=True),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "task_progress",
            sa.Enum("TODO", "IN_PROGRESS", "DONE", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("progress_ratio", sa.Integer(), nullable=False),
        sa.Column("progress_comment", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "subtasks",
        sa.Column("subtask_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("subtask_name", sa.String(length=30), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="subtaskpriority"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subtask_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subtasks")
    op.drop_table("tasks")
    op.drop_table("users")

    subtask_priority_enum = sa.Enum("HIGH", "MEDIUM", "LOW", name="subtaskpriority")
    task_status_enum = sa.Enum("TODO", "IN_PROGRESS", "DONE", name="taskstatus")

    connection = op.get_bind()

    subtask_priority_enum.drop(connection)
    task_status_enum.drop(connection)
    # ### end Alembic commands ###
